# managed-by: golden-path v1
name: PR actions
permissions:
  contents: read
'on':
  pull_request:
    branches:
      - master

jobs:
  danger-ci:
    name: Danger CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
        env:
          RUNNER_TEMP: /tmp
      - name: Danger CI
        uses: vtex/danger@master
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          REQUIRE_CHANGELOG_VERSION: false
  io-app-test:
    name: IO app test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
        env:
          RUNNER_TEMP: /tmp
      - name: Run test on every builder directory
        uses: vtex/action-io-app-test@v1.0.1
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
        env:
          RUNNER_TEMP: /tmp
      - name: Lint project
        uses: vtex/action-lint@v1.1.1
